repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "79"]
