FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ARG PROJECT_URL
ARG API_KEY
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG JWT_SECRET_KEY

ENV PROJECT_URL=$PROJECT_URL
ENV API_KEY=$API_KEY
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY

CMD ["python", "app.py"]
